# Reusable workflow to upload artifacts to a Google Cloud Storage bucket
#
# This workflow uses OpenID Connect (OIDC) to authenticate with GCP

name: Upload Artifacts to Google Cloud Storage
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      pack_names:
        required: true
        type: string
      packs_directory:
        required: true
        type: string
    secrets:
      bucket_name:
        required: true
      workload_identity_provider:
        required: true
      service_account:
        required: true
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      BRANCH_NAME: ${{ inputs.branch_name }}
      PACK_NAMES: ${{ inputs.pack_names }}
      PACKS_DIRECTORY: ${{ inputs.packs_directory }}
      BUCKET_NAME: ${{ secrets.bucket_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}

      - name: Upload Packs to Artifacts Server
        run : |
          echo "Uploading packs ${PACK_NAMES}..."
          python $GITHUB_WORKSPACE/repository/build_related_scripts/bucket_upload.py \
            --bucket_name "${BUCKET_NAME}" \
            --service_account "${SERVICE_ACCOUNT}" \
            --packs_directory "${PACKS_DIRECTORY}" \
            --branch_name "${PACK_NAMES}"
