# Reusable workflow to upload artifacts to an AWS S3 bucket
#
# This workflow uses OpenID Connect (OIDC) to authenticate with AWS

name: Upload Artifacts to AWS S3
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      pack_names:
        required: true
        type: string
      packs_directory:
        required: true
        type: string
    secrets:
      bucket_name:
        required: true
      aws_assume_role:
        required: true
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      BRANCH_NAME: ${{ inputs.branch_name }}
      PACK_NAMES: ${{ inputs.pack_names }}
      PACKS_DIRECTORY: ${{ inputs.packs_directory }}
      BUCKET_NAME: ${{ secrets.bucket_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws_assume_role }}
          aws-region: "us-east-1"
      - name: Upload Packs to Artifacts Server
        run : |
          echo "Uploading packs ${PACK_NAMES}..."
          python $GITHUB_WORKSPACE/repository/build_related_scripts/bucket_upload_s3.py \
            --bucket_name "${BUCKET_NAME}" \
            --packs_directory "${PACKS_DIRECTORY}" \
            --branch_name "${PACK_NAMES}" \
            --verbose
